version: '3.9'

services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    environment:
      # Essas informacoes podem estar no .env
      RABBITMQ_DEFAULT_USER: "admin" 
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  postgres:
    image: "postgres:16.4-alpine3.20"
    restart: always
    environment:
      POSTGRES_USER: "gesthor"
      POSTGRES_PASSWORD: "Estoqu3"
      POSTGRES_DB: "gesthor"
    ports:
      - "5432:5432"