services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    environment:
      # Essas informacoes podem estar no .env
      RABBITMQ_DEFAULT_USER: "admin" 
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  postgres:
    image: "postgres:16.4-alpine3.20"
    restart: always
    environment:
      POSTGRES_USER: "gesthor"
      POSTGRES_PASSWORD: "Estoqu3"
      POSTGRES_DB: "gesthor"
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    environment:
    - REDIS_REPLICATION_MODE=master
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      node_net:
        ipv4_address: 172.28.1.4

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16